-- Create sequence for supplier_code
CREATE SEQUENCE public.supplier_code_seq START 1;

-- Create suppliers table
CREATE TABLE public.suppliers (
    id bigint generated by default as identity primary key,
    supplier_code text UNIQUE NOT NULL,
    name text NOT NULL CHECK (trim(name) <> ''),
    contact_person text,
    email text,
    phone text,
    address text,
    notes text,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid NOT NULL REFERENCES auth.users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indices for fast searching and filtering
CREATE INDEX idx_suppliers_name ON public.suppliers(name);
CREATE INDEX idx_suppliers_supplier_code ON public.suppliers(supplier_code);
CREATE INDEX idx_suppliers_is_active ON public.suppliers(is_active);

-- Trigger to auto-generate supplier_code like SUP-0001
CREATE OR REPLACE FUNCTION public.generate_supplier_code()
RETURNS trigger AS $$
BEGIN
    IF NEW.supplier_code IS NULL OR NEW.supplier_code = '' THEN
        NEW.supplier_code := 'SUP-' || LPAD(nextval('public.supplier_code_seq')::text, 4, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_supplier_code
BEFORE INSERT ON public.suppliers
FOR EACH ROW
EXECUTE FUNCTION public.generate_supplier_code();

-- Trigger to automatically update updated_at
CREATE OR REPLACE FUNCTION public.update_supplier_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_supplier_updated_at
BEFORE UPDATE ON public.suppliers
FOR EACH ROW
EXECUTE FUNCTION public.update_supplier_updated_at();

-- ENABLE ROW LEVEL SECURITY
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

-- 1. SELECT: Allowed for admin, inventory_manager
CREATE POLICY "Admin and Inventory Manager can view suppliers"
ON public.suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.staff_profiles
        WHERE staff_profiles.id = auth.uid()
        AND staff_profiles.is_active = true
        AND staff_profiles.role IN ('admin', 'inventory_manager')
    )
);

-- 2. INSERT: Allowed for admin, inventory_manager
CREATE POLICY "Admin and Inventory Manager can insert suppliers"
ON public.suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.staff_profiles
        WHERE staff_profiles.id = auth.uid()
        AND staff_profiles.is_active = true
        AND staff_profiles.role IN ('admin', 'inventory_manager')
    )
);

-- 3. UPDATE: Allowed for admin, inventory_manager
CREATE POLICY "Admin and Inventory Manager can update suppliers"
ON public.suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.staff_profiles
        WHERE staff_profiles.id = auth.uid()
        AND staff_profiles.is_active = true
        AND staff_profiles.role IN ('admin', 'inventory_manager')
    )
);

-- 4. PREVENT NON-ADMIN FROM MODIFYING is_active directly via normal UPDATE
-- We'll use a trigger to check if is_active is being changed and reject if not admin
CREATE OR REPLACE FUNCTION public.protect_supplier_activation()
RETURNS trigger AS $$
DECLARE
    v_role text;
    v_is_active boolean;
BEGIN
    IF OLD.is_active IS DISTINCT FROM NEW.is_active THEN
        SELECT role, is_active INTO v_role, v_is_active
        FROM public.staff_profiles
        WHERE id = auth.uid();

        IF NOT FOUND OR NOT v_is_active OR v_role <> 'admin' THEN
            RAISE EXCEPTION 'Unauthorized: Only active Admins can activate or deactivate suppliers directly.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_protect_supplier_activation
BEFORE UPDATE ON public.suppliers
FOR EACH ROW
EXECUTE FUNCTION public.protect_supplier_activation();


-- SECURE RPC: set_supplier_active_status
-- This provides a formal API for Admins to activate/deactivate
CREATE OR REPLACE FUNCTION public.set_supplier_active_status(
    p_supplier_id bigint,
    p_is_active boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_role text;
    v_user_active boolean;
BEGIN
    -- 1. Check if user is authenticated
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    -- 2. Validate that user is an Admin
    SELECT role, is_active INTO v_role, v_user_active
    FROM public.staff_profiles
    WHERE id = auth.uid();

    IF NOT FOUND OR NOT v_user_active OR v_role <> 'admin' THEN
        RAISE EXCEPTION 'Unauthorized: Only active Admins can change supplier status.';
    END IF;

    -- 3. Update the supplier
    -- This update bypasses RLS but our trigger trg_protect_supplier_activation will still fire.
    -- However, because auth.uid() is an admin here, the trigger allows it.
    UPDATE public.suppliers
    SET is_active = p_is_active
    WHERE id = p_supplier_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier not found';
    END IF;
END;
$$;
